services:
  backend:
    build: ./backend/
    networks:
      - net
    depends_on:
      - database
  
  database:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      TZ: Europe/Moscow
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - net

networks:
  net:
      